import { DiagnosticBlock } from "../types";

export const block03Marketing: DiagnosticBlock = {
  id: "marketing-mercado",
  title: "Marketing y Mercado",
  subtitle: "Generación de demanda, mensaje y posicionamiento",
  description:
    "Este bloque mide si la empresa genera demanda de forma consistente y entiende su mercado.",
  weight: 100,
  allowNotApplicable: true,
  questions: [
    {
      id: "cliente-ideal",
      title: "¿Qué tan claramente está definido el cliente ideal?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "Nada claro",
      scaleMaxLabel: "Muy claro",
      evidence: [
        { id: "buyer-persona", label: "Tiene buyer persona definido" },
        { id: "segmentacion-clara", label: "Segmenta su mercado" },
        { id: "entiende-necesidades", label: "Entiende necesidades del cliente" },
        { id: "diferencia-publicos", label: "Diferencia públicos o segmentos" },
        { id: "habla-a-todos", label: "Comunica a todos por igual" },
      ],
    },
    {
      id: "generacion-demanda",
      title: "¿La empresa genera leads o demanda de forma constante?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "Nada constante",
      scaleMaxLabel: "Muy constante",
      evidence: [
        { id: "capta-leads", label: "Capta leads o contactos comerciales" },
        { id: "tiene-campanas", label: "Hace campañas regularmente" },
        { id: "usa-varios-canales", label: "Usa varios canales de atracción" },
        { id: "mide-resultados-captacion", label: "Mide resultados de captación" },
        { id: "depende-del-azar", label: "La demanda depende del boca a boca o del azar" },
      ],
    },
    {
      id: "canales-adquisicion",
      title: "¿Existen canales de marketing definidos y funcionando?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "No existen",
      scaleMaxLabel: "Muy consolidados",
      evidence: [
        { id: "redes-sociales", label: "Usa redes sociales activamente" },
        { id: "publicidad-paga", label: "Usa publicidad paga" },
        { id: "canal-organico", label: "Tiene canal orgánico funcionando" },
        { id: "canal-referidos", label: "Genera referidos o recomendaciones" },
        { id: "sin-canales-definidos", label: "No tiene canales claros" },
      ],
    },
    {
      id: "consistencia-marca",
      title: "¿La comunicación de la empresa es clara y coherente en todos los canales?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Muy inconsistente",
      scaleMaxLabel: "Muy consistente",
      evidence: [
        { id: "mensaje-claro", label: "Tiene mensaje claro" },
        { id: "identidad-visual-coherente", label: "Mantiene identidad visual coherente" },
        { id: "propuesta-bien-comunicada", label: "Comunica bien su propuesta de valor" },
        { id: "tono-unificado", label: "Mantiene tono consistente" },
        { id: "comunicacion-confusa", label: "La comunicación es confusa o cambiante" },
      ],
    },
    {
      id: "medicion-marketing",
      title: "¿La empresa sabe qué acciones de marketing le generan clientes y cuáles no?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "No sabe",
      scaleMaxLabel: "Lo sabe y optimiza",
      evidence: [
        { id: "mide-leads", label: "Mide leads generados" },
        { id: "mide-costo-lead", label: "Mide costo por lead" },
        { id: "mide-conversion-marketing", label: "Mide conversión por canal" },
        { id: "mide-ventas-por-canal", label: "Mide ventas por canal" },
        { id: "sin-medicion", label: "No sabe qué acciones funcionan" },
      ],
      hasNotes: true,
    },
    {
      id: "dependencia-canal",
      title: "¿Qué tan dependiente es la empresa de un solo canal de adquisición?",
      type: "multiple",
      weight: 15,
      allowNotApplicable: true,
      choices: [
        { id: "total", label: "Totalmente dependiente", points: 5 },
        { id: "alta", label: "Alta dependencia", points: 10 },
        { id: "diversificado", label: "Diversificado", points: 15 },
      ],
      evidence: [
        { id: "varios-canales", label: "Opera en varios canales" },
        { id: "canal-dominante", label: "Un canal concentra la mayoría de resultados" },
        { id: "evalua-riesgo-canal", label: "Evalúa riesgo por dependencia de canal" },
        { id: "sin-diversificacion", label: "No trabaja diversificación" },
      ],
    },
  ],
};