import { DiagnosticBlock } from "../types";

export const block06Produccion: DiagnosticBlock = {
  id: "produccion",
  title: "Producción",
  subtitle: "Planificación, costos, calidad y capacidad productiva",
  description:
    "Este bloque mide el nivel de control que tiene la empresa sobre su proceso productivo.",
  weight: 100,
  allowNotApplicable: true,
  questions: [
    {
      id: "planificacion-produccion",
      title: "¿Qué tan planificada está la producción?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "Muy reactiva",
      scaleMaxLabel: "Muy planificada",
      evidence: [
        { id: "planificacion-semanal", label: "Tiene planificación semanal o mensual" },
        { id: "usa-proyecciones-demanda", label: "Usa proyecciones de demanda" },
        { id: "ajusta-segun-ventas", label: "Ajusta producción según ventas" },
        { id: "coordina-comercial-logistica", label: "Coordina con comercial y logística" },
        { id: "produce-reactivo", label: "Produce de forma reactiva" },
      ],
    },
    {
      id: "costos-produccion",
      title: "¿Qué nivel de control tiene sobre los costos de producción?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "Muy poco control",
      scaleMaxLabel: "Control total",
      evidence: [
        { id: "costo-por-producto", label: "Conoce costo por producto" },
        { id: "actualiza-costos", label: "Actualiza costos regularmente" },
        { id: "estructura-costos-clara", label: "Tiene estructura de costos clara" },
        { id: "controla-variaciones", label: "Controla variaciones de costo" },
        { id: "no-conoce-costos", label: "No conoce bien sus costos" },
      ],
    },
    {
      id: "eficiencia-productiva",
      title: "¿Qué tan eficiente es el proceso productivo?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Muy ineficiente",
      scaleMaxLabel: "Muy eficiente",
      evidence: [
        { id: "mide-tiempos-produccion", label: "Mide tiempos de producción" },
        { id: "controla-rendimiento", label: "Controla rendimiento" },
        { id: "optimiza-insumos", label: "Optimiza uso de insumos" },
        { id: "reduce-tiempos-muertos", label: "Reduce tiempos muertos" },
        { id: "no-mide-eficiencia", label: "No mide eficiencia" },
      ],
    },
    {
      id: "control-calidad",
      title: "¿Qué tan consistente es la calidad del producto?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Muy inconsistente",
      scaleMaxLabel: "Muy consistente",
      evidence: [
        { id: "estandares-definidos", label: "Tiene estándares definidos" },
        { id: "realiza-controles-calidad", label: "Realiza controles de calidad" },
        { id: "registra-fallas", label: "Registra fallas" },
        { id: "procesos-correctivos", label: "Tiene procesos correctivos" },
        { id: "no-controla-calidad", label: "No controla calidad" },
      ],
    },
    {
      id: "mermas-desperdicios-produccion",
      title: "¿Qué nivel de control tiene sobre mermas y desperdicios en producción?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Ningún control",
      scaleMaxLabel: "Control total",
      evidence: [
        { id: "mide-mermas-produccion", label: "Mide mermas" },
        { id: "registra-desperdicios", label: "Registra desperdicios" },
        { id: "analiza-causas-merma", label: "Analiza causas" },
        { id: "implementa-mejoras-merma", label: "Implementa mejoras" },
        { id: "sin-control-mermas", label: "No tiene control" },
      ],
    },
    {
      id: "capacidad-productiva",
      title: "¿La empresa puede aumentar producción sin afectar calidad ni costos?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "No puede",
      scaleMaxLabel: "Sí, claramente",
      evidence: [
        { id: "capacidad-ociosa", label: "Tiene capacidad ociosa" },
        { id: "puede-escalar-produccion", label: "Puede escalar producción" },
        { id: "procesos-replicables-produccion", label: "Tiene procesos replicables" },
        { id: "puede-tercerizar", label: "Puede tercerizar si hace falta" },
        { id: "no-puede-escalar-produccion", label: "No puede escalar" },
      ],
    },
    {
      id: "dependencia-personal-clave-produccion",
      title: "¿Qué tan dependiente es la producción de personas clave?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Muy dependiente",
      scaleMaxLabel: "Poca dependencia",
      evidence: [
        { id: "operarios-conocimiento-critico", label: "Hay operarios con conocimiento crítico" },
        { id: "knowhow-no-documentado", label: "No existe documentación del know-how" },
        { id: "produccion-se-detiene", label: "La producción se detiene si falta una persona" },
        { id: "capacitacion-cruzada", label: "Existe capacitación cruzada" },
        { id: "procesos-reducen-dependencia", label: "Los procesos documentados reducen dependencia" },
        { id: "sin-dependencia-relevante", label: "No hay dependencia relevante" },
      ],
    },
  ],
};