import { DiagnosticBlock } from "../types";

export const block09Finanzas: DiagnosticBlock = {
  id: "finanzas",
  title: "Finanzas",
  subtitle: "Caja, rentabilidad, costos, deuda y planificación financiera",
  description:
    "Este bloque mide si la empresa entiende, controla y protege su dinero con criterio real de gestión.",
  weight: 100,
  allowNotApplicable: true,
  questions: [
    {
      id: "claridad-financiera",
      title: "¿Qué tan claro tiene la empresa su situación financiera real?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Nada clara",
      scaleMaxLabel: "Muy clara",
      evidence: [
        { id: "estado-resultados-actualizado", label: "Tiene estado de resultados actualizado" },
        { id: "flujo-caja-visible", label: "Tiene flujo de caja visible" },
        { id: "separa-ingresos-costos-gastos", label: "Separa ingresos, costos y gastos" },
        { id: "revision-financiera-frecuente", label: "Revisa información financiera con frecuencia" },
        { id: "explica-situacion-financiera", label: "Puede explicar su situación financiera con claridad" },
        { id: "sin-claridad-financiera", label: "No tiene claridad financiera real" },
      ],
      hasNotes: true,
    },
    {
      id: "flujo-caja",
      title: "¿Qué tan controlado está el flujo de caja de la empresa?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "Nada controlado",
      scaleMaxLabel: "Muy controlado",
      evidence: [
        { id: "proyecta-cobros-pagos", label: "Proyecta cobros y pagos" },
        { id: "conoce-saldo-real", label: "Conoce su saldo disponible real" },
        { id: "anticipa-faltantes-excedentes", label: "Sabe cuándo tendrá faltantes o excedentes" },
        { id: "controla-vencimientos", label: "Controla vencimientos" },
        { id: "actualiza-caja-semanal", label: "Actualiza caja semanalmente o con mayor frecuencia" },
        { id: "no-proyecta-caja", label: "No proyecta caja" },
      ],
    },
    {
      id: "rentabilidad-real",
      title: "¿Qué tan bien entiende la empresa cuáles productos, servicios o clientes le dejan realmente dinero?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "No lo entiende",
      scaleMaxLabel: "Lo entiende muy bien",
      evidence: [
        { id: "margen-por-producto", label: "Conoce margen por producto o servicio" },
        { id: "margen-por-cliente", label: "Conoce margen por cliente o canal" },
        { id: "separa-ventas-rentabilidad", label: "Separa ventas de rentabilidad" },
        { id: "identifica-lineas-poco-rentables", label: "Identifica líneas poco rentables" },
        { id: "usa-rentabilidad-para-decidir", label: "Usa esta información para decidir" },
        { id: "no-conoce-rentabilidad-real", label: "No conoce su rentabilidad real" },
      ],
    },
    {
      id: "costos-gastos",
      title: "¿Qué tan controlados y entendidos están los costos y gastos del negocio?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Muy poco controlados",
      scaleMaxLabel: "Muy controlados",
      evidence: [
        { id: "diferencia-fijos-variables", label: "Diferencia costos fijos y variables" },
        { id: "estructura-costos-clara", label: "Tiene estructura de costos clara" },
        { id: "controla-gastos-operativos", label: "Controla gastos operativos" },
        { id: "revisa-desvios-presupuesto", label: "Revisa desvíos contra presupuesto o plan" },
        { id: "detecta-gastos-innecesarios", label: "Detecta gastos innecesarios" },
        { id: "sin-estructura-costos", label: "No tiene estructura clara de costos y gastos" },
      ],
    },
    {
      id: "presupuesto-planificacion-financiera",
      title: "¿Qué tan planificada financieramente está la empresa?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Nada planificada",
      scaleMaxLabel: "Muy planificada",
      evidence: [
        { id: "presupuesto-anual-mensual", label: "Tiene presupuesto anual o mensual" },
        { id: "proyecta-ventas-costos-gastos", label: "Proyecta ventas, costos y gastos" },
        { id: "revisa-desvios-financieros", label: "Revisa desvíos" },
        { id: "ajusta-decisiones-segun-resultados", label: "Ajusta decisiones según resultados" },
        { id: "planifica-inversiones", label: "Planifica inversiones" },
        { id: "no-trabaja-presupuesto", label: "No trabaja con presupuesto" },
      ],
    },
    {
      id: "endeudamiento",
      title: "¿Qué tan sana y controlada está la carga financiera de la empresa?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Muy descontrolada",
      scaleMaxLabel: "Muy controlada",
      evidence: [
        { id: "conoce-deudas-compromisos", label: "Conoce todas sus deudas y compromisos" },
        { id: "calendario-pagos-financieros", label: "Tiene calendario de pagos" },
        { id: "mide-capacidad-pago", label: "Mide capacidad de pago" },
        { id: "controla-intereses-costos-financieros", label: "Controla intereses y costos financieros" },
        { id: "renegocia-cuando-necesita", label: "Renegocia cuando es necesario" },
        { id: "sin-control-endeudamiento", label: "No tiene control real del endeudamiento" },
      ],
    },
    {
      id: "cobranza-cuentas-por-cobrar",
      title: "¿Qué tan bien gestiona la empresa el cobro de lo que vende?",
      type: "scale",
      weight: 5,
      allowNotApplicable: true,
      scaleMinLabel: "Muy mal",
      scaleMaxLabel: "Muy bien",
      evidence: [
        { id: "politica-cobranza", label: "Tiene política de cobranza" },
        { id: "seguimiento-cxc", label: "Hace seguimiento a cuentas por cobrar" },
        { id: "mide-mora", label: "Mide mora" },
        { id: "conoce-antiguedad-saldos", label: "Conoce antigüedad de saldos" },
        { id: "acciones-recuperacion", label: "Activa acciones de recuperación" },
        { id: "sin-control-cobranza", label: "No controla cuentas por cobrar" },
      ],
    },
    {
      id: "pagos-cuentas-por-pagar",
      title: "¿Qué tan ordenada está la empresa con sus pagos y obligaciones?",
      type: "scale",
      weight: 5,
      allowNotApplicable: true,
      scaleMinLabel: "Muy desordenada",
      scaleMaxLabel: "Muy ordenada",
      evidence: [
        { id: "calendario-pagos", label: "Tiene calendario de pagos" },
        { id: "prioriza-pagos", label: "Prioriza pagos según criterio financiero" },
        { id: "evita-recargos-atrasos", label: "Evita recargos o atrasos" },
        { id: "controla-obligaciones-proveedores", label: "Controla obligaciones con proveedores" },
        { id: "previsibilidad-egresos", label: "Tiene previsibilidad de egresos" },
        { id: "paga-reactivo", label: "Paga de forma reactiva" },
      ],
    },
    {
      id: "formalidad-contable-fiscal",
      title: "¿Qué tan ordenada está la empresa en materia contable e impositiva?",
      type: "scale",
      weight: 5,
      allowNotApplicable: true,
      scaleMinLabel: "Muy desordenada",
      scaleMaxLabel: "Muy ordenada",
      evidence: [
        { id: "registra-operaciones-correctamente", label: "Registra operaciones correctamente" },
        { id: "cierre-contable-periodico", label: "Tiene cierre contable periódico" },
        { id: "cumple-obligaciones-fiscales", label: "Cumple obligaciones fiscales" },
        { id: "trabaja-con-contabilidad", label: "Trabaja coordinadamente con contabilidad" },
        { id: "info-contable-utilizable", label: "Tiene información contable utilizable" },
        { id: "contabilidad-solo-cumplimiento", label: "La contabilidad solo se usa para cumplir" },
      ],
    },
    {
      id: "capacidad-inversion-crecimiento",
      title: "¿Qué tan preparada está la empresa para financiar su crecimiento?",
      type: "scale",
      weight: 5,
      allowNotApplicable: true,
      scaleMinLabel: "Nada preparada",
      scaleMaxLabel: "Muy preparada",
      evidence: [
        { id: "genera-excedente-reinversion", label: "Genera excedente para reinversión" },
        { id: "identifica-capacidad-inversion", label: "Puede identificar cuánto puede invertir" },
        { id: "evalua-retorno-inversion", label: "Evalúa retorno esperado" },
        { id: "acceso-financiamiento", label: "Tiene acceso a financiamiento" },
        { id: "prioriza-inversiones", label: "Prioriza inversiones con criterio" },
        { id: "sin-capacidad-inversion", label: "No tiene capacidad ni criterio de inversión" },
      ],
    },
  ],
};