import { DiagnosticBlock } from "../types";

export const block10RRHH: DiagnosticBlock = {
  id: "rrhh",
  title: "Recursos Humanos",
  subtitle: "Roles, desempeño, cultura, estabilidad y profesionalización",
  description:
    "Este bloque mide si la empresa gestiona personas como sistema o si depende de la improvisación.",
  weight: 100,
  allowNotApplicable: true,
  questions: [
    {
      id: "roles-responsabilidades",
      title: "¿Qué tan claros están los roles y responsabilidades dentro de la empresa?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Muy confusos",
      scaleMaxLabel: "Muy claros",
      evidence: [
        { id: "descripciones-puesto", label: "Tiene descripciones de puesto" },
        { id: "roles-definidos-por-area", label: "Tiene roles definidos por área" },
        { id: "responsabilidades-claras-equipo", label: "Tiene responsabilidades claras" },
        { id: "expectativas-claras", label: "Cada persona sabe qué se espera de ella" },
        { id: "solapamientos-confusion", label: "Existen solapamientos o confusión" },
        { id: "sin-claridad-roles", label: "No hay claridad de roles" },
      ],
    },
    {
      id: "reclutamiento-seleccion",
      title: "¿Qué tan estructurado es el proceso de contratación?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Muy improvisado",
      scaleMaxLabel: "Muy estructurado",
      evidence: [
        { id: "proceso-seleccion-definido", label: "Tiene proceso definido de selección" },
        { id: "define-perfil-antes-contratar", label: "Define perfil antes de contratar" },
        { id: "evalua-candidatos-criterio", label: "Evalúa candidatos con criterio" },
        { id: "compara-opciones", label: "Compara opciones antes de decidir" },
        { id: "registra-procesos-seleccion", label: "Registra procesos de selección" },
        { id: "contrata-improvisado", label: "Contrata de forma improvisada" },
      ],
    },
    {
      id: "evaluacion-desempeno",
      title: "¿Qué tan bien mide la empresa el desempeño de su equipo?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "No lo mide",
      scaleMaxLabel: "Lo mide muy bien",
      evidence: [
        { id: "indicadores-por-puesto", label: "Tiene indicadores por puesto" },
        { id: "evaluaciones-periodicas", label: "Realiza evaluaciones periódicas" },
        { id: "feedback-estructurado", label: "Da feedback estructurado" },
        { id: "mide-resultados-individuales", label: "Mide resultados individuales" },
        { id: "decisiones-basadas-desempeno", label: "Toma decisiones basadas en desempeño" },
        { id: "no-mide-desempeno", label: "No mide desempeño" },
      ],
    },
    {
      id: "capacitacion-desarrollo",
      title: "¿Qué tan desarrolladas están las capacidades del equipo?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Muy poco desarrolladas",
      scaleMaxLabel: "Muy desarrolladas",
      evidence: [
        { id: "capacita-regularmente", label: "Capacita regularmente" },
        { id: "plan-formacion", label: "Tiene plan de formación" },
        { id: "desarrolla-habilidades-clave", label: "Desarrolla habilidades clave" },
        { id: "entrena-procesos-internos", label: "Entrena en procesos internos" },
        { id: "invierte-crecimiento-equipo", label: "Invierte en crecimiento del equipo" },
        { id: "no-capacita", label: "No capacita" },
      ],
    },
    {
      id: "cultura-clima",
      title: "¿Qué tan saludable y alineado es el clima laboral?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Muy deteriorado",
      scaleMaxLabel: "Muy saludable",
      evidence: [
        { id: "valores-definidos", label: "Tiene valores definidos" },
        { id: "buen-ambiente-laboral", label: "Existe buen ambiente laboral" },
        { id: "comunicacion-interna", label: "Hay comunicación interna" },
        { id: "gestiona-conflictos", label: "Gestiona conflictos" },
        { id: "escucha-al-equipo", label: "Escucha al equipo" },
        { id: "problemas-clima", label: "Hay problemas de clima" },
      ],
    },
    {
      id: "dependencia-dueno-lideres-rrhh",
      title: "¿Qué tan dependiente es el equipo del dueño o líderes para funcionar?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Totalmente dependiente",
      scaleMaxLabel: "Muy autónomo",
      evidence: [
        { id: "equipo-toma-decisiones", label: "El equipo toma decisiones" },
        { id: "autonomia-operativa", label: "Existe autonomía operativa" },
        { id: "lideres-intermedios-rrhh", label: "Tiene líderes intermedios" },
        { id: "delegacion-correcta-rrhh", label: "Se delega correctamente" },
        { id: "dueno-interviene-constante", label: "El dueño interviene constantemente" },
        { id: "sin-dueno-se-detiene", label: "Sin el dueño, la operación se detiene" },
      ],
    },
    {
      id: "rotacion-estabilidad",
      title: "¿Qué tan estable es el equipo de trabajo?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Muy inestable",
      scaleMaxLabel: "Muy estable",
      evidence: [
        { id: "baja-rotacion", label: "Tiene baja rotación" },
        { id: "retiene-talento-clave", label: "Retiene talento clave" },
        { id: "identifica-causas-salida", label: "Identifica causas de salida" },
        { id: "continuidad-equipos", label: "Tiene continuidad en equipos" },
        { id: "reemplaza-posiciones-rapido", label: "Reemplaza posiciones con rapidez" },
        { id: "alta-rotacion", label: "Tiene alta rotación sin control" },
      ],
    },
    {
      id: "incentivos-motivacion",
      title: "¿Qué tan alineados están los incentivos con los objetivos de la empresa?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Nada alineados",
      scaleMaxLabel: "Muy alineados",
      evidence: [
        { id: "esquema-incentivos", label: "Tiene esquema de incentivos" },
        { id: "relaciona-desempeno-recompensas", label: "Relaciona desempeño con recompensas" },
        { id: "reconoce-resultados", label: "Reconoce resultados" },
        { id: "motiva-con-objetivos", label: "Motiva con objetivos claros" },
        { id: "seguimiento-resultados-rrhh", label: "Hace seguimiento de resultados" },
        { id: "sin-incentivos-claros", label: "No hay incentivos claros" },
      ],
    },
    {
      id: "profesionalizacion-equipo",
      title: "¿Qué tan profesionalizada está la estructura del equipo?",
      type: "scale",
      weight: 5,
      allowNotApplicable: true,
      scaleMinLabel: "Muy informal",
      scaleMaxLabel: "Muy profesionalizada",
      evidence: [
        { id: "estructura-organizacional-definida", label: "Tiene estructura organizacional definida" },
        { id: "jerarquias-claras", label: "Tiene jerarquías claras" },
        { id: "responsables-por-area", label: "Existen responsables por área" },
        { id: "se-respeta-estructura", label: "Se respeta la estructura" },
        { id: "evoluciona-con-crecimiento", label: "La estructura evoluciona con el crecimiento" },
        { id: "estructura-informal-caotica", label: "La estructura es informal o caótica" },
      ],
    },
  ],
};