import { DiagnosticBlock } from "../types";

export const block04Cliente: DiagnosticBlock = {
  id: "cliente-cx-postventa",
  title: "Cliente (CX y Postventa)",
  subtitle: "Experiencia, retención y gestión del cliente",
  description:
    "Este bloque mide la calidad de experiencia que vive el cliente y la capacidad de la empresa para retenerlo.",
  weight: 100,
  allowNotApplicable: true,
  questions: [
    {
      id: "conocimiento-cliente",
      title: "¿Qué tan bien conoce la empresa a sus clientes?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "Los conoce muy poco",
      scaleMaxLabel: "Los conoce muy bien",
      evidence: [
        { id: "perfiles-definidos", label: "Tiene perfiles de cliente definidos" },
        { id: "analiza-compra", label: "Analiza comportamiento de compra" },
        { id: "base-datos-clientes", label: "Tiene base de datos de clientes" },
        { id: "segmenta-clientes", label: "Segmenta clientes" },
        { id: "sin-informacion", label: "No tiene información clara del cliente" },
      ],
    },
    {
      id: "experiencia-cliente",
      title: "¿Qué tan buena es la experiencia que recibe el cliente en todo el proceso?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "Muy deficiente",
      scaleMaxLabel: "Excelente",
      evidence: [
        { id: "procesos-atencion", label: "Tiene procesos definidos de atención" },
        { id: "mide-satisfaccion", label: "Mide satisfacción del cliente" },
        { id: "gestiona-reclamos", label: "Recibe y gestiona reclamos" },
        { id: "capacita-atencion", label: "Capacita al equipo en atención" },
        { id: "disena-experiencia-premium", label: "Diseña experiencias diferenciales / premium" },
        { id: "personaliza-experiencia", label: "Personaliza la experiencia según el cliente" },
        { id: "no-mide-experiencia", label: "No mide experiencia" },
      ],
    },
    {
      id: "retencion-clientes",
      title: "¿Qué tan bien la empresa logra que los clientes vuelvan a comprar?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Muy mal",
      scaleMaxLabel: "Muy bien",
      evidence: [
        { id: "mide-recompra", label: "Mide clientes recurrentes" },
        { id: "fidelizacion", label: "Tiene programas de fidelización" },
        { id: "seguimiento-postventa", label: "Hace seguimiento postventa" },
        { id: "base-activa", label: "Tiene base activa de clientes" },
        { id: "no-trabaja-retencion", label: "No trabaja retención" },
      ],
    },
    {
      id: "gestion-reclamos",
      title: "¿Cómo gestiona la empresa los problemas o reclamos de clientes?",
      type: "multiple",
      weight: 15,
      allowNotApplicable: true,
      choices: [
        { id: "sin-proceso", label: "No hay proceso", points: 5 },
        { id: "reactivo", label: "Reactivo", points: 10 },
        { id: "definido", label: "Proceso definido", points: 15 },
      ],
      evidence: [
        { id: "registra-reclamos", label: "Registra reclamos" },
        { id: "define-responsables", label: "Define responsables" },
        { id: "hace-seguimiento", label: "Hace seguimiento hasta resolución" },
        { id: "aprende-de-reclamos", label: "Aprende de reclamos" },
      ],
    },
    {
      id: "canales-atencion",
      title: "¿Qué tan organizados están los canales de atención al cliente?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Desorganizados",
      scaleMaxLabel: "Muy organizados",
      evidence: [
        { id: "multiples-canales", label: "Usa múltiples canales" },
        { id: "centralizacion", label: "Centraliza atención en CRM o sistema" },
        { id: "tiempos-definidos", label: "Responde en tiempos definidos" },
        { id: "mide-respuesta", label: "Mide tiempos de respuesta" },
        { id: "desorganizado", label: "La atención está desorganizada" },
      ],
    },
    {
      id: "uso-feedback",
      title: "¿La empresa utiliza el feedback del cliente para mejorar?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "No lo usa",
      scaleMaxLabel: "Lo usa constantemente",
      evidence: [
        { id: "recoge-feedback", label: "Recoge feedback regularmente" },
        { id: "analiza-feedback", label: "Lo analiza" },
        { id: "implementa-mejoras", label: "Implementa mejoras" },
        { id: "comunica-cambios", label: "Comunica cambios" },
        { id: "eleva-experiencia", label: "Usa feedback para elevar la experiencia" },
        { id: "no-usa-feedback", label: "No utiliza feedback" },
      ],
    },
  ],
};