import { DiagnosticBlock } from "../types";

export const block01Direccion: DiagnosticBlock = {
  id: "direccion-estrategia",
  title: "Dirección y Estrategia",
  subtitle: "Claridad, liderazgo y capacidad real de dirección",
  description:
    "Este bloque mide si la empresa tiene rumbo, seguimiento y un liderazgo capaz de sostener crecimiento.",
  weight: 100,
  allowNotApplicable: true,
  questions: [
    {
      id: "claridad-estrategica",
      title: "¿La empresa tiene una estrategia clara y definida a 12–24 meses?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "No existe",
      scaleMaxLabel: "Muy clara y comunicada",
      evidence: [
        { id: "plan-estrategico", label: "Tiene plan estratégico definido" },
        { id: "objetivos-anuales", label: "Tiene objetivos anuales definidos" },
        { id: "prioridades-claves", label: "Define prioridades estratégicas" },
        { id: "comunicacion-interna", label: "Comunica la estrategia al equipo" },
        { id: "sin-rumbo", label: "Opera sin dirección clara" },
      ],
      hasNotes: true,
    },
    {
      id: "objetivos-medibles",
      title: "¿Existen objetivos concretos, medibles y con responsables asignados?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "No existen",
      scaleMaxLabel: "Totalmente definidos",
      evidence: [
        { id: "objetivos-por-area", label: "Tiene objetivos por área" },
        { id: "responsables-asignados", label: "Asigna responsables claros" },
        { id: "metas-medibles", label: "Trabaja con metas medibles" },
        { id: "seguimiento-objetivos", label: "Hace seguimiento periódico" },
        { id: "sin-objetivos-formales", label: "No tiene objetivos formales" },
      ],
    },
    {
      id: "alineacion-directiva",
      title: "¿El equipo directivo está alineado con la estrategia y objetivos?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Nada alineado",
      scaleMaxLabel: "Completamente alineado",
      evidence: [
        { id: "reuniones-direccion", label: "Tiene reuniones periódicas de dirección" },
        { id: "prioridades-compartidas", label: "Comparte prioridades entre líderes" },
        { id: "decisiones-alineadas", label: "Las decisiones siguen la estrategia" },
        { id: "conflicto-entre-areas", label: "Hay desalineación entre áreas" },
      ],
    },
    {
      id: "toma-decisiones",
      title: "¿Cómo se toman las decisiones clave en la empresa?",
      type: "multiple",
      weight: 10,
      allowNotApplicable: true,
      choices: [
        { id: "reactiva", label: "Reactiva / improvisada", points: 5 },
        { id: "experiencia", label: "Basada en experiencia", points: 8 },
        { id: "datos", label: "Basada en datos", points: 10 },
      ],
      evidence: [
        { id: "usa-reportes", label: "Usa reportes o indicadores" },
        { id: "consulta-equipo", label: "Consulta a líderes o responsables" },
        { id: "analiza-escenarios", label: "Analiza escenarios antes de decidir" },
        { id: "decide-sobre-la-marcha", label: "Decide sobre la marcha" },
      ],
    },
    {
      id: "seguimiento-kpis",
      title: "¿Se realiza seguimiento periódico de resultados del negocio?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "No se hace",
      scaleMaxLabel: "Se sigue de forma constante",
      evidence: [
        { id: "kpis-definidos", label: "Tiene KPI’s definidos" },
        { id: "tablero-control", label: "Usa tablero o reportes de seguimiento" },
        { id: "revision-semanal", label: "Hace revisión semanal o mensual" },
        { id: "acciones-correctivas", label: "Actúa ante desvíos" },
        { id: "sin-seguimiento", label: "No hace seguimiento real" },
      ],
    },
    {
      id: "dependencia-dueno",
      title: "¿Qué tan dependiente es la empresa del dueño o director para operar?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "Totalmente dependiente",
      scaleMaxLabel: "Opera con autonomía",
      evidence: [
        { id: "dueno-decide-todo", label: "El dueño decide casi todo" },
        { id: "equipo-autonomo", label: "El equipo puede operar sin intervención constante" },
        { id: "lideres-intermedios", label: "Tiene líderes intermedios funcionales" },
        { id: "delegacion-real", label: "Existe delegación real" },
        { id: "operacion-se-detiene", label: "Sin el dueño la operación se frena" },
      ],
    },
    {
      id: "capacidad-lider",
      title: "¿Qué tan preparado está el líder para dirigir y escalar la empresa?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "Muy reactivo",
      scaleMaxLabel: "Liderazgo de alto nivel",
      evidence: [
        { id: "vision-clara", label: "Tiene visión clara del negocio" },
        { id: "delega-correctamente", label: "Delega correctamente" },
        { id: "gestiona-con-datos", label: "Gestiona con datos" },
        { id: "forma-equipo", label: "Desarrolla y alinea al equipo" },
        { id: "apaga-incendios", label: "Pasa la mayor parte del tiempo apagando incendios" },
      ],
      hasNotes: true,
    },
  ],
};