import { DiagnosticBlock } from "../types";

export const block07Logistica: DiagnosticBlock = {
  id: "logistica-supply-chain",
  title: "Logística y Supply Chain",
  subtitle: "Inventario, abastecimiento, entregas y pérdidas logísticas",
  description:
    "Este bloque mide la capacidad de la empresa para mover, abastecer y controlar su flujo físico con eficiencia.",
  weight: 100,
  allowNotApplicable: true,
  questions: [
    {
      id: "gestion-inventarios",
      title: "¿Qué tan controlado está el inventario?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "Muy descontrolado",
      scaleMaxLabel: "Muy controlado",
      evidence: [
        { id: "stock-actualizado", label: "Tiene stock actualizado" },
        { id: "conteos-periodicos", label: "Realiza conteos periódicos" },
        { id: "sistema-inventario", label: "Usa sistema para controlar inventario" },
        { id: "controla-entradas-salidas", label: "Controla entradas y salidas" },
        { id: "detecta-diferencias-stock", label: "Detecta diferencias de stock" },
        { id: "sin-control-inventario", label: "No tiene control de inventario" },
      ],
    },
    {
      id: "abastecimiento-compras",
      title: "¿Qué tan eficiente es el proceso de compras y abastecimiento?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Muy reactivo",
      scaleMaxLabel: "Muy eficiente",
      evidence: [
        { id: "planifica-compras", label: "Planifica compras" },
        { id: "proveedores-definidos", label: "Tiene proveedores definidos" },
        { id: "compara-precios", label: "Compara precios y condiciones" },
        { id: "controla-tiempo-entrega", label: "Controla tiempos de entrega" },
        { id: "evalua-proveedores", label: "Evalúa desempeño de proveedores" },
        { id: "compra-reactivo", label: "Compra de forma reactiva" },
      ],
    },
    {
      id: "rupturas-stock",
      title: "¿Qué tan frecuente es quedarse sin stock de productos clave?",
      type: "multiple",
      weight: 15,
      allowNotApplicable: true,
      choices: [
        { id: "muy-frecuente", label: "Muy frecuente", points: 5 },
        { id: "ocasional", label: "Ocasional", points: 10 },
        { id: "raro", label: "Raro o inexistente", points: 15 },
      ],
      evidence: [
        { id: "identifica-productos-criticos", label: "Identifica productos críticos" },
        { id: "registra-quiebres", label: "Registra quiebres de stock" },
        { id: "analiza-causas-quiebre", label: "Analiza causas" },
        { id: "acciones-preventivas-quiebre", label: "Toma acciones preventivas" },
        { id: "no-lleva-registro", label: "No lleva registro" },
      ],
    },
    {
      id: "tiempos-entrega",
      title: "¿Qué tan eficientes son los tiempos de entrega al cliente o a la operación?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Muy ineficientes",
      scaleMaxLabel: "Muy eficientes",
      evidence: [
        { id: "tiempos-objetivo", label: "Tiene tiempos objetivo definidos" },
        { id: "cumple-plazos-entrega", label: "Cumple plazos de entrega" },
        { id: "mide-tiempos-reales", label: "Mide tiempos reales" },
        { id: "optimiza-rutas", label: "Optimiza rutas o recorridos" },
        { id: "seguimiento-entregas", label: "Hace seguimiento de entregas" },
        { id: "no-controla-tiempos", label: "No controla tiempos" },
      ],
    },
    {
      id: "costos-logisticos",
      title: "¿Qué nivel de control tiene la empresa sobre los costos logísticos?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "No controla",
      scaleMaxLabel: "Control total",
      evidence: [
        { id: "mide-transporte", label: "Mide costos de transporte" },
        { id: "mide-almacenamiento", label: "Mide costos de almacenamiento" },
        { id: "costo-por-entrega", label: "Calcula costo por entrega o pedido" },
        { id: "analiza-desvios-logisticos", label: "Analiza desvíos" },
        { id: "optimiza-costos-logisticos", label: "Toma acciones para optimizar" },
        { id: "sin-control-costos-logisticos", label: "No controla costos logísticos" },
      ],
    },
    {
      id: "dependencia-proveedores",
      title: "¿Qué tan dependiente es la empresa de pocos proveedores clave?",
      type: "multiple",
      weight: 10,
      allowNotApplicable: true,
      choices: [
        { id: "alta-dependencia", label: "Alta dependencia", points: 5 },
        { id: "dependencia-media", label: "Dependencia media", points: 7 },
        { id: "diversificado", label: "Proveedores diversificados", points: 10 },
      ],
      evidence: [
        { id: "proveedores-alternativos", label: "Tiene proveedores alternativos" },
        { id: "evalua-riesgo-abastecimiento", label: "Evalúa riesgo de abastecimiento" },
        { id: "negocia-multiples-opciones", label: "Negocia con más de una opción" },
        { id: "depende-pocos-proveedores", label: "Depende de uno o dos proveedores críticos" },
        { id: "sin-plan-alternativo", label: "No tiene plan alternativo" },
      ],
    },
    {
      id: "perdidas-robos-logisticos",
      title: "¿Qué nivel de control tiene la empresa sobre pérdidas logísticas, robos o desvíos de inventario?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Ningún control",
      scaleMaxLabel: "Control total",
      evidence: [
        { id: "registra-perdidas-inventario", label: "Registra pérdidas de inventario" },
        { id: "investiga-diferencias", label: "Investiga diferencias" },
        { id: "control-despacho-recepcion", label: "Tiene controles de despacho y recepción" },
        { id: "auditorias-conteos-cruzados", label: "Hace auditorías o conteos cruzados" },
        { id: "acciones-correctivas-logisticas", label: "Toma acciones correctivas" },
        { id: "sin-visibilidad-perdidas", label: "No tiene visibilidad sobre pérdidas" },
      ],
    },
    {
      id: "coordinacion-logistica",
      title: "¿Qué tan integrada está la logística con ventas, operaciones y compras?",
      type: "scale",
      weight: 5,
      allowNotApplicable: true,
      scaleMinLabel: "Muy desconectada",
      scaleMaxLabel: "Muy integrada",
      evidence: [
        { id: "comparte-informacion-areas", label: "Comparte información entre áreas" },
        { id: "coordina-planificacion-logistica", label: "Coordina planificación" },
        { id: "ajusta-demanda-logistica", label: "Ajusta logística según demanda" },
        { id: "seguimiento-conjunto", label: "Tiene reuniones o seguimiento conjunto" },
        { id: "desconexion-areas", label: "Hay desconexión entre áreas" },
      ],
    },
  ],
};