import { DiagnosticBlock } from "../types";

export const block08Tecnologia: DiagnosticBlock = {
  id: "tecnologia-data",
  title: "Tecnología y Data",
  subtitle: "Digitalización, sistemas, datos, automatización e IA",
  description:
    "Este bloque mide si la tecnología y los datos sostienen la operación o impulsan la transformación del negocio.",
  weight: 100,
  allowNotApplicable: true,
  questions: [
    {
      id: "digitalizacion-operativa",
      title: "¿Qué tan digitalizados están los procesos clave de la empresa?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Muy manuales",
      scaleMaxLabel: "Muy digitalizados",
      evidence: [
        { id: "usa-sistemas-procesos", label: "Usa sistemas para procesos importantes" },
        { id: "evita-papel-whatsapp", label: "Evita depender de papel o WhatsApp informal" },
        { id: "registra-info-digital", label: "Registra información de forma digital" },
        { id: "trazabilidad-tareas", label: "Tiene trazabilidad de tareas o movimientos" },
        { id: "datos-centralizados", label: "Tiene datos centralizados" },
        { id: "operacion-manual", label: "La operación sigue siendo mayormente manual" },
      ],
    },
    {
      id: "calidad-datos",
      title: "¿Qué tan confiables, ordenados y útiles son los datos de la empresa para tomar decisiones?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Muy desordenados",
      scaleMaxLabel: "Muy confiables",
      evidence: [
        { id: "bases-actualizadas", label: "Tiene bases de datos actualizadas" },
        { id: "informacion-limpia", label: "La información está limpia y ordenada" },
        { id: "responsables-carga", label: "Existen responsables de carga o control" },
        { id: "consulta-facil", label: "Los datos se pueden consultar fácilmente" },
        { id: "criterios-unificados", label: "Existen criterios unificados de registro" },
        { id: "datos-incompletos", label: "Los datos están incompletos o desordenados" },
      ],
    },
    {
      id: "sistemas-gestion",
      title: "¿Qué tan bien apoyan los sistemas actuales a la operación del negocio?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Apoyan muy poco",
      scaleMaxLabel: "Apoyan muy bien",
      evidence: [
        { id: "usa-erp-crm", label: "Usa ERP, CRM o sistemas equivalentes" },
        { id: "cubre-procesos-criticos", label: "Los sistemas cubren procesos críticos" },
        { id: "usuarios-usan-sistema", label: "Los usuarios los utilizan realmente" },
        { id: "info-ayuda-decidir", label: "La información del sistema ayuda a decidir" },
        { id: "reportes-utiles", label: "Existen reportes útiles" },
        { id: "sistemas-no-acompanan", label: "Los sistemas no acompañan bien la operación" },
      ],
    },
    {
      id: "integracion-sistemas-areas",
      title: "¿Qué tan conectados están los sistemas y la información entre las distintas áreas?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Muy desconectados",
      scaleMaxLabel: "Muy integrados",
      evidence: [
        { id: "areas-comparten-info", label: "Las áreas comparten información" },
        { id: "integracion-sistemas", label: "Hay integración entre sistemas" },
        { id: "evita-carga-duplicada", label: "Se evita carga duplicada" },
        { id: "flujo-informacion-procesos", label: "La información fluye entre procesos" },
        { id: "automatizaciones-entre-areas", label: "Existen automatizaciones entre áreas" },
        { id: "areas-aisladas", label: "Cada área trabaja aislada" },
      ],
    },
    {
      id: "medicion-analitica",
      title: "¿Qué tan bien usa la empresa los datos para medir su desempeño y tomar decisiones?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "No usa datos",
      scaleMaxLabel: "Usa datos constantemente",
      evidence: [
        { id: "kpis-definidos-data", label: "Tiene KPI’s definidos" },
        { id: "usa-tableros", label: "Usa tableros o reportes periódicos" },
        { id: "analiza-tendencias", label: "Analiza tendencias" },
        { id: "detecta-desvios-con-datos", label: "Detecta desvíos con datos" },
        { id: "decide-con-informacion", label: "Toma decisiones basadas en información" },
        { id: "decide-sin-datos", label: "Decide sin apoyo de datos" },
      ],
    },
    {
      id: "seguridad-informacion",
      title: "¿Qué tan protegida y resguardada está la información de la empresa?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Muy expuesta",
      scaleMaxLabel: "Muy protegida",
      evidence: [
        { id: "tiene-backups", label: "Tiene backups" },
        { id: "controla-accesos", label: "Controla accesos por usuario" },
        { id: "permisos-por-rol", label: "Define permisos según rol" },
        { id: "protege-datos-sensibles", label: "Protege datos sensibles" },
        { id: "politicas-seguridad", label: "Tiene políticas básicas de seguridad" },
        { id: "sin-control-informacion", label: "No existe control claro sobre la información" },
      ],
    },
    {
      id: "automatizacion",
      title: "¿Qué tanto aprovecha la empresa la automatización para reducir trabajo manual y errores?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Nada",
      scaleMaxLabel: "Mucho",
      evidence: [
        { id: "automatiza-repetitivas", label: "Automatiza tareas repetitivas" },
        { id: "reduce-carga-manual", label: "Reduce carga manual entre áreas" },
        { id: "flujos-automaticos", label: "Usa flujos o integraciones automáticas" },
        { id: "disminuye-errores", label: "Disminuye errores por automatización" },
        { id: "ahorra-tiempo", label: "Ahorra tiempo con tecnología" },
        { id: "todo-manual", label: "Casi todo se hace manualmente" },
      ],
    },
    {
      id: "vision-transformacion-digital-ia",
      title: "¿Qué tan preparada está la empresa para avanzar en transformación digital, automatización e inteligencia artificial?",
      type: "scale",
      weight: 5,
      allowNotApplicable: true,
      scaleMinLabel: "Nada preparada",
      scaleMaxLabel: "Muy preparada",
      evidence: [
        { id: "apertura-cambio", label: "Tiene apertura al cambio" },
        { id: "identifica-oportunidades", label: "Identifica oportunidades tecnológicas" },
        { id: "profesionalizar-antes-escalar", label: "Quiere profesionalizar procesos antes de escalar" },
        { id: "ve-tecnologia-estrategica", label: "Ve la tecnología como inversión estratégica" },
        { id: "interes-ia", label: "Tiene interés en IA o automatización" },
        { id: "sin-vision-digital", label: "No tiene visión digital clara" },
      ],
    },
  ],
};