import { DiagnosticBlock } from "../types";

export const block05Operaciones: DiagnosticBlock = {
  id: "operaciones",
  title: "Operaciones",
  subtitle: "Ejecución diaria, eficiencia y control operativo",
  description:
    "Este bloque mide la capacidad de la empresa para operar con orden, control, eficiencia y escalabilidad.",
  weight: 100,
  allowNotApplicable: true,
  questions: [
    {
      id: "claridad-operativa",
      title: "¿Qué tan claras están las tareas y responsabilidades en la operación diaria?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Muy confusas",
      scaleMaxLabel: "Muy claras",
      evidence: [
        { id: "roles-definidos", label: "Tiene roles definidos" },
        { id: "responsabilidades-claras", label: "Tiene responsabilidades claras" },
        { id: "flujo-trabajo-conocido", label: "El flujo de trabajo es conocido" },
        { id: "supervision-activa", label: "Existe supervisión activa" },
        { id: "desorden-operativo", label: "Hay desorden operativo" },
      ],
    },
    {
      id: "estandarizacion-operaciones",
      title: "¿Qué tan estandarizadas están las operaciones?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "Nada estandarizadas",
      scaleMaxLabel: "Muy estandarizadas",
      evidence: [
        { id: "procesos-documentados", label: "Tiene procesos documentados" },
        { id: "manuales-operativos", label: "Tiene manuales operativos" },
        { id: "procedimientos-repetibles", label: "Tiene procedimientos repetibles" },
        { id: "capacitacion-procesos", label: "Capacita en base a procesos" },
        { id: "sin-estandarizacion", label: "No existe estandarización" },
      ],
    },
    {
      id: "control-operativo",
      title: "¿Qué nivel de control tiene la empresa sobre su operación?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "Muy poco control",
      scaleMaxLabel: "Control total",
      evidence: [
        { id: "indicadores-operativos", label: "Tiene indicadores operativos definidos" },
        { id: "seguimiento-diario", label: "Hace seguimiento diario o semanal" },
        { id: "reportes-operativos", label: "Genera reportes operativos" },
        { id: "usa-sistemas", label: "Usa sistemas para controlar la operación" },
        { id: "falta-control", label: "Hay falta de control operativo" },
      ],
    },
    {
      id: "eficiencia-operativa",
      title: "¿Qué tan eficiente es la operación en tiempo, costos y recursos?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Muy ineficiente",
      scaleMaxLabel: "Muy eficiente",
      evidence: [
        { id: "mide-tiempos-operativos", label: "Mide tiempos operativos" },
        { id: "controla-costos-operativos", label: "Controla costos operativos" },
        { id: "optimiza-recursos", label: "Optimiza uso de recursos" },
        { id: "detecta-desperdicios", label: "Detecta desperdicios" },
        { id: "mide-mermas", label: "Mide mermas o pérdidas" },
        { id: "controla-desvios", label: "Controla desvíos vs presupuesto o estándar" },
        { id: "reduce-perdidas", label: "Implementa acciones para reducir pérdidas" },
        { id: "no-mide-eficiencia", label: "No mide eficiencia" },
      ],
    },
    {
      id: "resolucion-problemas",
      title: "¿Cómo responde la empresa ante problemas operativos?",
      type: "multiple",
      weight: 10,
      allowNotApplicable: true,
      choices: [
        { id: "reactivo", label: "Reacciona apagando incendios", points: 5 },
        { id: "experiencia", label: "Resuelve por experiencia", points: 8 },
        { id: "proceso", label: "Tiene procesos definidos para resolver", points: 10 },
      ],
      evidence: [
        { id: "escala-incidentes", label: "Escala incidentes con criterio" },
        { id: "analiza-causa-raiz", label: "Analiza causa raíz" },
        { id: "define-correcciones", label: "Define acciones correctivas" },
        { id: "repite-problemas", label: "Los mismos problemas se repiten" },
      ],
    },
    {
      id: "escalabilidad-operativa",
      title: "¿La operación puede crecer sin perder control ni calidad?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "No puede",
      scaleMaxLabel: "Sí, claramente",
      evidence: [
        { id: "aumenta-volumen", label: "Puede aumentar volumen sin colapsar" },
        { id: "capacidad-instalada", label: "Tiene capacidad instalada" },
        { id: "procesos-replicables", label: "Tiene procesos replicables" },
        { id: "puede-delegar", label: "Puede delegar operación" },
        { id: "no-puede-escalar", label: "No puede escalar sin desorden" },
      ],
    },
    {
      id: "costos-ocultos-perdidas",
      title: "¿Qué nivel de control tiene la empresa sobre pérdidas operativas no visibles?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "No tiene visibilidad",
      scaleMaxLabel: "Tiene control claro",
      evidence: [
        { id: "identifica-mermas", label: "Identifica mermas de producto, tiempo o dinero" },
        { id: "registra-perdidas", label: "Registra pérdidas regularmente" },
        { id: "indicadores-perdida", label: "Tiene indicadores de pérdida" },
        { id: "acciones-correctivas-perdidas", label: "Toma acciones correctivas" },
        { id: "integra-perdidas-decision", label: "Integra pérdidas en sus decisiones" },
        { id: "sin-visibilidad", label: "No tiene visibilidad sobre pérdidas ocultas" },
      ],
    },
  ],
};