import { DiagnosticBlock } from "../types";

export const block02Comercial: DiagnosticBlock = {
  id: "comercial-crecimiento",
  title: "Comercial y Crecimiento",
  subtitle: "Ventas, previsibilidad y escalabilidad comercial",
  description:
    "Este bloque mide la capacidad real de generar ingresos de forma estructurada y sostenible.",
  weight: 100,
  allowNotApplicable: true,
  questions: [
    {
      id: "modelo-comercial",
      title: "¿Está claramente definido cómo la empresa genera ingresos?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "Nada claro",
      scaleMaxLabel: "Muy claro",
      evidence: [
        { id: "propuesta-valor", label: "Tiene propuesta de valor definida" },
        { id: "cliente-objetivo", label: "Tiene cliente objetivo identificado" },
        { id: "oferta-clara", label: "Tiene oferta comercial clara" },
        { id: "canales-definidos", label: "Tiene canales de venta definidos" },
        { id: "modelo-difuso", label: "El modelo comercial es confuso" },
      ],
    },
    {
      id: "pipeline-ventas",
      title: "¿La empresa cuenta con un pipeline comercial activo y predecible?",
      type: "scale",
      weight: 20,
      allowNotApplicable: true,
      scaleMinLabel: "No existe",
      scaleMaxLabel: "Muy predecible",
      evidence: [
        { id: "pipeline-activo", label: "Tiene pipeline activo" },
        { id: "oportunidades-etapas", label: "Gestiona oportunidades por etapas" },
        { id: "seguimiento-comercial", label: "Hace seguimiento comercial" },
        { id: "pronostico-ventas", label: "Tiene previsión de ventas" },
        { id: "ventas-improvisadas", label: "Las ventas se generan sin estructura" },
      ],
    },
    {
      id: "conversion-comercial",
      title: "¿Qué tan efectiva es la conversión de leads a clientes?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Muy baja",
      scaleMaxLabel: "Muy alta",
      evidence: [
        { id: "mide-conversion", label: "Mide tasa de conversión" },
        { id: "seguimiento-leads", label: "Hace seguimiento a leads" },
        { id: "argumento-comercial", label: "Tiene argumento comercial claro" },
        { id: "objeciones-registradas", label: "Identifica objeciones frecuentes" },
        { id: "no-mide-conversion", label: "No mide conversión" },
      ],
      hasNotes: true,
    },
    {
      id: "dependencia-clientes",
      title: "¿Qué nivel de dependencia existe en pocos clientes?",
      type: "multiple",
      weight: 15,
      allowNotApplicable: true,
      choices: [
        { id: "alta", label: "Más del 70% depende de 1–3 clientes", points: 5 },
        { id: "media", label: "Entre 40% y 70%", points: 10 },
        { id: "baja", label: "Menos del 40%, cartera diversificada", points: 15 },
      ],
      evidence: [
        { id: "analiza-concentracion", label: "Analiza concentración de clientes" },
        { id: "diversifica-cartera", label: "Busca diversificar cartera" },
        { id: "tiene-clientes-clave", label: "Tiene clientes clave identificados" },
        { id: "alta-exposicion", label: "La facturación depende de pocos clientes" },
      ],
    },
    {
      id: "proceso-comercial",
      title: "¿Existe un proceso comercial definido y replicable?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "No existe",
      scaleMaxLabel: "Muy estructurado",
      evidence: [
        { id: "etapas-definidas", label: "Tiene etapas comerciales definidas" },
        { id: "usa-crm", label: "Usa CRM o sistema equivalente" },
        { id: "seguimiento-oportunidades", label: "Hace seguimiento a oportunidades" },
        { id: "responsables-comerciales", label: "Tiene responsables comerciales claros" },
        { id: "sin-proceso", label: "No tiene proceso comercial formal" },
      ],
    },
    {
      id: "capacidad-crecimiento",
      title: "¿La empresa puede escalar ventas sin colapsar su operación?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "No puede",
      scaleMaxLabel: "Sí, claramente",
      evidence: [
        { id: "operacion-sostiene-crecimiento", label: "La operación puede sostener más ventas" },
        { id: "equipo-comercial-capaz", label: "El equipo comercial puede crecer" },
        { id: "oferta-escalable", label: "La oferta es escalable" },
        { id: "cuellos-de-botella-detectados", label: "Tiene identificados cuellos de botella" },
        { id: "crecer-desordena", label: "Crecer genera desorden o incumplimientos" },
      ],
    },
  ],
};