import { DiagnosticBlock } from "../types";

export const block11Procesos: DiagnosticBlock = {
  id: "procesos",
  title: "Procesos y Estandarización",
  subtitle: "Documentación, repetibilidad y control del negocio",
  description:
    "Este bloque mide si la empresa funciona con procesos claros o depende de personas y memoria.",
  weight: 100,
  allowNotApplicable: true,
  questions: [
    {
      id: "procesos-clave-definidos",
      title: "¿La empresa tiene definidos sus procesos clave de punta a punta?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "No existen",
      scaleMaxLabel: "Muy claros",
      evidence: [
        { id: "identifica-procesos-clave", label: "Identifica procesos clave" },
        { id: "mapas-proceso", label: "Tiene mapas de proceso" },
        { id: "flujo-end-to-end", label: "Tiene flujo de punta a punta definido" },
        { id: "responsables-proceso", label: "Tiene responsables por proceso" },
        { id: "visualiza-flujos", label: "Puede visualizar cómo fluye el negocio" },
        { id: "sin-procesos-definidos", label: "No tiene procesos definidos" },
      ],
    },
    {
      id: "documentacion-procesos",
      title: "¿Qué tan documentados están los procesos?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Nada documentados",
      scaleMaxLabel: "Muy documentados",
      evidence: [
        { id: "manuales-procedimientos", label: "Tiene manuales o procedimientos escritos" },
        { id: "instrucciones-operativas", label: "Tiene instrucciones operativas claras" },
        { id: "documentacion-accesible", label: "La documentación es accesible" },
        { id: "actualiza-documentacion", label: "Actualiza la documentación" },
        { id: "versionado-procesos", label: "Controla versiones de procesos" },
        { id: "todo-dependencia-personas", label: "Depende de memoria de las personas" },
      ],
    },
    {
      id: "estandarizacion-procesos",
      title: "¿Qué tan estandarizada es la forma de trabajar?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Nada estandarizada",
      scaleMaxLabel: "Muy estandarizada",
      evidence: [
        { id: "todos-trabajan-igual", label: "Las personas trabajan de forma consistente" },
        { id: "reduce-variabilidad", label: "Reduce variabilidad en resultados" },
        { id: "usa-checklists", label: "Usa checklists o guías" },
        { id: "aplica-buenas-practicas", label: "Aplica buenas prácticas" },
        { id: "procesos-replicables", label: "Los procesos son replicables" },
        { id: "cada-uno-trabaja-distinto", label: "Cada persona trabaja diferente" },
      ],
    },
    {
      id: "control-ejecucion-procesos",
      title: "¿Qué tan controlada está la ejecución de los procesos?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Sin control",
      scaleMaxLabel: "Muy controlada",
      evidence: [
        { id: "mide-cumplimiento-procesos", label: "Mide cumplimiento de procesos" },
        { id: "detecta-desvios-procesos", label: "Detecta desvíos" },
        { id: "corrige-errores", label: "Corrige errores sistemáticamente" },
        { id: "auditorias-internas", label: "Realiza auditorías internas" },
        { id: "responsables-control", label: "Hay responsables de control" },
        { id: "no-controla-ejecucion", label: "No controla ejecución" },
      ],
    },
    {
      id: "mejora-continua",
      title: "¿Qué tan activa es la mejora continua dentro de la empresa?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "No existe",
      scaleMaxLabel: "Muy activa",
      evidence: [
        { id: "propone-mejoras", label: "El equipo propone mejoras" },
        { id: "analiza-problemas", label: "Analiza problemas recurrentes" },
        { id: "implementa-mejoras", label: "Implementa mejoras" },
        { id: "mide-impacto-mejoras", label: "Mide impacto de mejoras" },
        { id: "aprende-de-errores", label: "Aprende de errores" },
        { id: "no-mejora", label: "No existe mejora continua" },
      ],
    },
    {
      id: "dependencia-personas-procesos",
      title: "¿Qué tan dependientes son los procesos de personas específicas?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Totalmente dependientes",
      scaleMaxLabel: "Independientes",
      evidence: [
        { id: "knowhow-documentado", label: "El know-how está documentado" },
        { id: "puede-reemplazar-personas", label: "Puede reemplazar personas sin fricción" },
        { id: "capacitacion-cruzada-procesos", label: "Existe capacitación cruzada" },
        { id: "procesos-estandarizados-reducen-dependencia", label: "Procesos reducen dependencia" },
        { id: "personas-clave-insustituibles", label: "Hay personas clave insustituibles" },
        { id: "operacion-se-detiene-sin-persona", label: "La operación se detiene si falta alguien" },
      ],
    },
    {
      id: "integracion-procesos",
      title: "¿Qué tan integrados están los procesos entre áreas?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Muy desconectados",
      scaleMaxLabel: "Muy integrados",
      evidence: [
        { id: "flujo-entre-areas", label: "Existe flujo entre áreas" },
        { id: "coordina-procesos", label: "Se coordinan procesos entre áreas" },
        { id: "evita-retrabajo", label: "Se evita retrabajo" },
        { id: "informacion-fluye", label: "La información fluye correctamente" },
        { id: "procesos-conectados", label: "Los procesos están conectados" },
        { id: "silos-operativos", label: "Cada área trabaja aislada" },
      ],
    },
    {
      id: "capacidad-escalar-procesos",
      title: "¿Los procesos permiten escalar la empresa sin perder control ni calidad?",
      type: "scale",
      weight: 5,
      allowNotApplicable: true,
      scaleMinLabel: "No permiten escalar",
      scaleMaxLabel: "Escalan muy bien",
      evidence: [
        { id: "procesos-replicables-escalar", label: "Los procesos son replicables" },
        { id: "soportan-crecimiento", label: "Soportan crecimiento" },
        { id: "mantiene-calidad", label: "Mantiene calidad al crecer" },
        { id: "reduce-error-crecimiento", label: "Reduce errores al crecer" },
        { id: "estructura-acompana-crecimiento", label: "La estructura acompaña el crecimiento" },
        { id: "crecer-genera-caos", label: "Crecer genera caos" },
      ],
    },
  ],
};