import { DiagnosticBlock } from "../types";

export const block12Riesgo: DiagnosticBlock = {
  id: "riesgo-control",
  title: "Riesgo y Control",
  subtitle: "Protección del negocio, controles internos y continuidad",
  description:
    "Este bloque mide qué tan expuesta o protegida está la empresa frente a errores, fraudes, crisis y riesgos invisibles.",
  weight: 100,
  allowNotApplicable: true,
  questions: [
    {
      id: "identificacion-riesgos",
      title: "¿Qué tan identificados están los principales riesgos del negocio?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Nada identificados",
      scaleMaxLabel: "Muy identificados",
      evidence: [
        { id: "identifica-riesgos-operativos", label: "Identifica riesgos operativos" },
        { id: "identifica-riesgos-financieros", label: "Identifica riesgos financieros" },
        { id: "identifica-riesgos-legales", label: "Identifica riesgos legales o regulatorios" },
        { id: "prioriza-riesgos", label: "Prioriza riesgos según impacto" },
        { id: "documenta-riesgos", label: "Documenta riesgos" },
        { id: "no-identifica-riesgos", label: "No identifica riesgos de forma clara" },
      ],
    },
    {
      id: "gestion-riesgos",
      title: "¿Qué tan preparada está la empresa para gestionar los riesgos identificados?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Nada preparada",
      scaleMaxLabel: "Muy preparada",
      evidence: [
        { id: "planes-mitigacion", label: "Tiene planes de mitigación" },
        { id: "acciones-preventivas", label: "Define acciones preventivas" },
        { id: "monitorea-riesgos", label: "Monitorea riesgos activos" },
        { id: "integra-riesgo-decisiones", label: "Integra riesgos en decisiones" },
        { id: "responsables-riesgo", label: "Tiene responsables asignados" },
        { id: "actua-cuando-ocurre", label: "Solo actúa cuando el problema ocurre" },
      ],
    },
    {
      id: "control-interno",
      title: "¿Qué tan sólidos son los controles internos del negocio?",
      type: "scale",
      weight: 15,
      allowNotApplicable: true,
      scaleMinLabel: "Muy débiles",
      scaleMaxLabel: "Muy sólidos",
      evidence: [
        { id: "controles-procesos-criticos", label: "Tiene controles en procesos críticos" },
        { id: "segregacion-funciones", label: "Tiene segregación de funciones" },
        { id: "define-responsables-control", label: "Define responsables de control" },
        { id: "valida-operaciones-clave", label: "Valida operaciones clave" },
        { id: "reduce-errores-fraudes", label: "Reduce errores y fraudes" },
        { id: "sin-controles-definidos", label: "No tiene controles definidos" },
      ],
    },
    {
      id: "auditoria-seguimiento",
      title: "¿Qué tan frecuentemente se revisa el cumplimiento y funcionamiento del negocio?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Casi nunca",
      scaleMaxLabel: "Muy frecuentemente",
      evidence: [
        { id: "auditorias-internas-riesgo", label: "Realiza auditorías internas" },
        { id: "revisiones-periodicas", label: "Hace revisiones periódicas" },
        { id: "detecta-fallas", label: "Detecta fallas" },
        { id: "aplica-correcciones", label: "Aplica correcciones" },
        { id: "seguimiento-mejoras", label: "Hace seguimiento de mejoras" },
        { id: "no-revisa", label: "No revisa procesos ni resultados" },
      ],
    },
    {
      id: "riesgos-financieros",
      title: "¿Qué tan expuesta está la empresa a riesgos financieros?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Muy expuesta",
      scaleMaxLabel: "Muy protegida",
      evidence: [
        { id: "controla-flujo-caja-riesgo", label: "Controla flujo de caja" },
        { id: "monitorea-endeudamiento-riesgo", label: "Monitorea endeudamiento" },
        { id: "evalua-escenarios-financieros", label: "Evalúa escenarios financieros" },
        { id: "tiene-reservas-colchon", label: "Tiene reservas o colchón financiero" },
        { id: "gestiona-liquidez", label: "Gestiona riesgo de liquidez" },
        { id: "sin-control-riesgo-financiero", label: "No controla riesgos financieros" },
      ],
    },
    {
      id: "riesgos-operativos",
      title: "¿Qué tan controlados están los riesgos en la operación diaria?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Muy descontrolados",
      scaleMaxLabel: "Muy controlados",
      evidence: [
        { id: "identifica-fallas-operativas", label: "Identifica fallas operativas" },
        { id: "planes-contingencia-operativos", label: "Tiene planes de contingencia" },
        { id: "reduce-errores-recurrentes", label: "Reduce errores recurrentes" },
        { id: "controla-interrupciones", label: "Controla interrupciones" },
        { id: "aprende-incidentes", label: "Aprende de incidentes" },
        { id: "sin-control-riesgos-operativos", label: "No controla riesgos operativos" },
      ],
    },
    {
      id: "cumplimiento-legal-normativo",
      title: "¿Qué tan alineada está la empresa con sus obligaciones legales y regulatorias?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Muy desalineada",
      scaleMaxLabel: "Muy alineada",
      evidence: [
        { id: "cumple-normativas", label: "Cumple normativas vigentes" },
        { id: "asesoramiento-legal-contable", label: "Tiene asesoramiento legal o contable" },
        { id: "actualiza-obligaciones", label: "Actualiza obligaciones" },
        { id: "evita-sanciones", label: "Evita sanciones" },
        { id: "documenta-cumplimiento", label: "Documenta cumplimiento" },
        { id: "cumple-reactivo", label: "Solo cumple de forma reactiva" },
      ],
    },
    {
      id: "continuidad-negocio",
      title: "¿Qué tan preparada está la empresa para continuar operando ante una crisis?",
      type: "scale",
      weight: 10,
      allowNotApplicable: true,
      scaleMinLabel: "Nada preparada",
      scaleMaxLabel: "Muy preparada",
      evidence: [
        { id: "planes-contingencia-crisis", label: "Tiene planes de contingencia" },
        { id: "puede-operar-con-fallas", label: "Puede operar ante fallas" },
        { id: "alternativas-operativas", label: "Tiene alternativas operativas" },
        { id: "adapta-cambios", label: "Puede adaptarse a cambios" },
        { id: "define-escenarios-crisis", label: "Define escenarios de crisis" },
        { id: "sin-preparacion-crisis", label: "No tiene preparación" },
      ],
    },
    {
      id: "seguridad-activos",
      title: "¿Qué tan protegidos están los activos físicos y digitales de la empresa?",
      type: "scale",
      weight: 5,
      allowNotApplicable: true,
      scaleMinLabel: "Muy expuestos",
      scaleMaxLabel: "Muy protegidos",
      evidence: [
        { id: "controla-accesos-fisicos", label: "Controla accesos físicos" },
        { id: "protege-inventarios-activos", label: "Protege inventarios y activos" },
        { id: "seguridad-digital-basica", label: "Tiene seguridad digital básica" },
        { id: "protege-informacion-sensible", label: "Protege información sensible" },
        { id: "politicas-seguridad-activos", label: "Tiene políticas de seguridad" },
        { id: "sin-proteccion-clara", label: "No tiene protección clara" },
      ],
    },
  ],
};